### ISSUE TITLE
[FEATURE] Animation's (Various)

### ISSUE THREAD

**Issue by N95JPL** [JPLogistics/JPLogistics_C152#60]
**Is your feature request related to a problem? Please describe.**
Create and implement opening doors..

**Describe the solution you'd like**
Don't think this comment is needed!

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by N95JPL** [comment]
Updating this Issue to be inclusive of all animations that are going to be added/changed

- [x] Sun Visors
   - [x] Pilot 
   - [x] CoPilot
   - [ ] Textures (Require more work)
- [ ] Doors
   - [x] Pilot 
   - [ ] CoPilot
- [ ] Windows
   - [x] Pilot 
   - [ ] CoPilot
- [x] Cabin Floodlight Switch
- [ ] Fix any animations that are currently broken (Various)
- [ ] Yoke Animation...very broken, main priority
- [ ] OAT Gauge Needle, needs calibrating

**Comment by EricFlight** [comment]
Can you make the seats go forward to access the back storage better and also the back pockets on the seats? We often put the POH, Weight and balance packet in the back pocket of the passenger seat (three clip small binder to hold all papers together). Also, GATS Jar and fuel hawk in back of the left PIC seat and maybe a rag back there in case we need it (used for checking oil if needed and general maintenance while on the go)

**Comment by EricFlight** [comment]
If you could have a cabin light that is red or the MSFS flashlight be red instead of white (or have a choice between red/white) for night time flying it would be nice. We do not use white light while flying at night to keep our vision for night. I often use a red light headlamp (which could be emulated with the MSFS flashlight) when flying at night in the 152.
