### ISSUE TITLE
[FEATURE] Engine Start “enhancement”

### ISSUE THREAD

**Issue by N95JPL** [JPLogistics/JPLogistics_C152#61]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Add features such as a functional/required prime before engine start, simulating exhaust and "failed starts" (due to not priming or running too rich)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by EricFlight** [comment]
Just a couple of notes here for this feature:

- Usually 2-3 pumps of the primer for operation are done at standard temperature. If the aircraft run in the past 30 minutes-1 hour we usually try to start it without priming as it might have enough in there to start.
- In cold weather, we usually have to prime it more 3 pumps..sometimes up to 5 to get it started
- In warm weather, we usually prime 2 pumps to get it started
- If it doesn't start, we might also push the throttle in and out 1-2 times to add fuel instead of the primer and then try again (not the safest but we do do it with understanding too much fuel = potential engine fire)
